---
editor_options:
  chunk_output_type: console
# output: bookdown::gitbook
# bibliography: "../web/book.bib"
---

## Continuous DA (CDA) {#DA-C}

There are three types of markets with continuous double auction being their main mechanisms:

- quote-driven continuous double auction market (CDA-Q)
- order-driven continuous double auction market (CDA-O)
- hybrid continuous double auction market (CDA-H)

> Electronic trading employing a public limit order book is continuing to gain a greater share of worldwide security trading and many of the major exchanges in the world rely, at least in part, upon limit orders for the provision of liquidity. [_chiarella2002simulation_]

> A market is efficient if it enables investors to trade quickly and cheaply and if it incorporates new information quickly and accurately into prices. [_foucault2013market_]

- __donier2016walras__ From Walras’ auctioneer to continuous time double auctions: a general dynamic theory of supply and demand
- __bouchaud2010how__ How markets slowly digest changes in supply and demand

### Real-World Market Operation

To design and implement a small-scale-friendly electricity market, the understanding of real-world market operation process is necessary.

> The way securities are actually traded is far removed from the idealized picture of a frictionless and self-equilibrating market offered by the typical finance textbook. In that idealized version of the trading process, all potential participants are present on the market; these participants convey to the market orders that reflect their demand or supply of securities, and they are not affected by actions of other market participants; and an auctioneer balances the quantities demanded and supplied at a single equilibrium price that reflects a consensus view of the security’s “fundamental value.” Real-world markets do not work like this, for two main reasons. [_foucault2013market_]
> - First, market players are not all simultaneously present on the market. Such continuous presence would be too costly in time, attention, and access costs. At any given point in time, price formation is delegated to the limited number of market participants who happen to be present. Any temporary imbalance between buy and sell orders for a security will have to be absorbed by whoever (p.2) is present, especially by professional intermediaries who specialize in “making the market.” Typically, market makers and other investors will absorb order imbalances only if the price is sufficiently attractive. For instance, to absorb a spate of sell orders investors will require the inducement of a sufficiently low price. As a result, the equilibrium price actually struck at any given instant may deviate from the one that would emerge if all investors participated. These price deviations generate profit opportunities, which in turn will draw in more traders. Over time the deviations are ironed out.
> - Second, even the limited number of participants who are present at any instant in a real-world security market have quite diverse information about the security’s fundamentals: some participants are shrewd market professionals with all the latest news and state-of- the-art pricing models at their fingertips; others do not have such up-to-date information but may try to infer it from the behavior of other participants; still others may trade for reasons that are unrelated to information, for instance a need to liquidate their holdings in order to pay their bills. As a result, the order flow is a complex mix of information and noise, and a consensus price only emerges over time, as the trading process evolves and participants interpret the actions of other traders. This is another reason why a security’s actual transaction price might deviate from its fundamental value, which would be assessed by a fully informed set of investors.

Electronic limit order market has been recognized as the best‐practice for trading small-scale orders.

### Order-Driven CDA

Liquidity is harder to measure than illiquidity because illiquidity is measured by trading cost, which composes explicit and implicit costs. The explicit cost is easy to determine, while the implicit cost is the difference between execution prices and benchmark prices.

### Why do People Trade

> Trading of securities may be prompted by various factors: [_foucault2013market_]
> - the need to mitigate risks (hedging)
> - the desire to exploit superior information (speculation)
> - the urge to rebalance one’s portfolio (liquidity shocks)

Forward trading in the electricity market:
- reserve the right to consume
- earn a profit as much as possible

### Case: Intraday Electricity Market

- [_weber2010adequate_] Adequate intraday market design to enable the integration of wind energy into the European power systems

> Basically however the easiness of trade is certainly an increasing function of the number of market participants and the number of trades. Therefore a frequently applied indicator for liquidity in financial and energy markets is the trading volume in a market. [_weber2010adequate_]

> Another kind of problem occurs in Denmark and the other Scandinavian countries, where the liquidity of the intraday market is also low. This is at least partly related to the fact, that producers can submit bids in unlimited quantities for the so-called balancing power market. Those bids do not receive a capacity price, yet they are included in the short-term merit order list of the grid operators and activated if economically attractive. However this system is not as problematic as it may seem: given the high share of hydro, flexible power capacity usually is not scarce in the Nordic power system. Consequently differences between day- ahead (or intraday) power prices and the balancing power prices are low. This implies that wind operators (provided they see a uniform balancing price) do not incur large losses, if their deviations are settled using balancing energy instead of intraday trade. More problematic is here that all Scandinavian countries except Norway use two-price models when it comes to charging the balancing energy. [_weber2010adequate_]

> Random information updates about intraday deviations from the day-ahead planning induce a need for an adjustment of schedules. [_weber2015trading_]

> In an efficient decentralized market design, market participants will always try to self balance unforeseen deviations from the day-ahead planning in order to avoid the costly usage of flexible resources in real-time balancing. [_weber2015trading_]

### Prediction Market

https://iemweb.biz.uiowa.edu/

> Prediction markets (also known as betting markets, political betting markets, predictive markets, information markets, decision markets, idea futures, event derivatives, or virtual markets) are exchange-traded markets created for the purpose of trading the outcome of events. The market prices can indicate what the crowd thinks the probability of the event is. A prediction market contract trades between 0 and 100%. It is a binary option that will expire at the price of 0 or 100%. Prediction markets can be thought of as belonging to the more general concept of crowdsourcing which is specially designed to aggregate information on particular topics of interest. The main purposes of prediction markets are eliciting aggregating beliefs over an unknown future outcome. Traders with different beliefs trade on contracts whose payoffs are related to the unknown future outcome and the market prices of the contracts are considered as the aggregated belief. [_Prediction Market, Wikipedia_]
