---
editor_options:
  chunk_output_type: console
# output: bookdown::gitbook
# bibliography: "../web/book.bib"
---

## Peer-to-Peer Markets (P@P) {#DA-P2P}

- __eckhardt2015sharing__ The Sharing Economy Isn’t About Sharing at All. https://hbr.org/2015/01/the-sharing-economy-isnt-about-sharing-at-all

> It implies that consumers are more interested in lower costs and convenience than they are in fostering social relationships with the company or other consumers. Companies that understand this will have a competitive advantage. For example, we are currently seeing the rise of Uber in the short-term car-ride market. Uber positions itself squarely around its pricing, reliability, and convenience. This is encapsulated in their tagline, “Better, faster and cheaper than a taxi.” In comparison, Lyft, which offers an almost identical service, positions itself as friendly (“We’re your friend with a car”), and as a community (“Greet your driver with a fistbump”). Lyft has not seen nearly the same amount of growth as Uber, and a contributing reason is because they are putting too much emphasis on consumers’ desire to “share” with each other. [_eckhardt2015sharing_]

> P2P energy-trading platforms allow prosumers to trade electrical energy with one another directly. Energy transactions could vary in terms of quantity, time-scale and acceptable variability, and may be network-location-specific. P2P energy trading is recognized as another potential structure for prosumer electricity markets. P2P trading platforms have emerged in a range of sectors, allowing small suppliers to compete with traditional providers of goods and services.


## Network Effects

https://www.lyft.com/driver/why-drive-with-lyft
