---
editor_options:
  chunk_output_type: console
---

## L-Shaped Benders Decomposition for Stochastic Programming {#De-benders-l}

The standard form for two stage stochastic programming with no integer variables in second stage can be expressed as:

$$ \begin{align}
\min_{\mathbf{y}, \mathbf{x}} \quad& \mathbf{f}^{T} \mathbf{y} + \sum_{s \in \Omega} \pi_s \mathbf{c}_s^T \mathbf{x}_s \\
\text{s.t.} \quad& \mathbf{t}_s \mathbf{y} + \mathbf{w}_s \mathbf{x}_s \geq \mathbf{h}_s \quad \forall s \in S \\
& \mathbf{y} \in \mathbf{Y} \\
& \mathbf{x}_s \geq 0 \quad \forall s \in S
\end{align} $$

where $\mathbf{y}$ is the vector of here-and-now decision variables, some of which are integer variables.

Master Problem:

$$ \begin{align}
\min_{\mathbf{y}, q} \quad& \mathbf{f} ^ {T} \mathbf{y} + q \\
\text{s.t.} \quad& \overline{\mathbf{u}_j^r}^T (\mathbf{h}_s - \mathbf{t}_s \mathbf{y}) \leq 0 \quad \forall j \\
& \overline{\mathbf{u}_i^p}^T (\mathbf{h}_s - \mathbf{t}_s \mathbf{y}) \leq q \quad \forall i \\
& \mathbf{y} \in \mathbf{Y}
\end{align} $$

Sub-problem for each scenario:

$$ \begin{align}
\min_{\mathbf{x}} \quad & \mathbf{c}_s^T \mathbf{x}_s \\
\text{s.t.} \quad & \mathbf{w}_s \mathbf{x}_s \geq \mathbf{h}_s - \mathbf{t}_s \overline{\mathbf{y}} \\
& \mathbf{x}_s \geq 0
\end{align} $$

Dual problem of the sub-problem is used, which can be expressed as:

$$ \begin{align}
\max_{\mathbf{u}} \quad & \left(\mathbf{h}_s - \mathbf{t}_s \overline{\mathbf{y}} \right)^T \mathbf{u}_s \\
\text{s.t.} \quad & \mathbf{w}_s^T \mathbf{u}_s \leq \mathbf{c}_{s} \\
& \mathbf{u}_s \geq 0
\end{align} $$

Then, when the sub-problem cannot be solved optimally because the feasible set is unbounded, ray-problem should be used instead, which can be expressed as:

$$ \begin{align}
\max_{\mathbf{u}} \quad & 1 \\
\text{s.t.} \quad & (\mathbf{h}_{s} - \mathbf{t}_{s} \overline{\mathbf{y}})^{T} \mathbf{u} = 1 \\
& \mathbf{w}_{s}^{T} \mathbf{u} \leq \mathbf{0} \\
& \mathbf{u}_s \geq 0
\end{align} $$

The aggregation of $\overline{\mathbf{u}}$ and $\text{obj}_{\text{sub}}$ from all scenarios are:

$$ \begin{align}
\overline{\mathbf{u}} &= \sum_{s \in \Omega} \pi_s \mathbf{u}_s \\
\text{obj}_{\text{sub}} &= \sum_{s \in \Omega} \pi_s \text{obj}_{\text{sub}, s} \\
\end{align} $$

### Example: News Boy problem

$$ \begin{align}
\max \quad & \sum_{s} \pi_{s}(p-h) x_{s}+\sum_{s} \pi_{s}(h-c) y \\
\text{s.t.} \quad & x_{s} \leq d_{s} \quad \forall s \\
& x_{s} \leq y \quad \forall s \\
& x \in R^{+} \\
& y \in Z^{+}
\end{align} $$

## L-Shaped Benders Decomposition with Integer Variables in Second Stage {#De-benders-l-int}

The standard form for two stage stochastic programming with integer variables in second stage:

$$ \begin{align}
\min_{\mathbf{y}, \mathbf{x}_s, \mathbf{z}_s} \quad& \mathbf{f} ^ { T } \mathbf{y} + \sum_{s \in \Omega} \pi_s \left(\mathbf{c}_s^T \mathbf{x}_s + \mathbf{d}_s^T \mathbf{z}_s \right) \\
\text{s.t.} \quad& \mathbf{T}_s \mathbf{y} + \mathbf{w}_s \mathbf{x}_s + \mathbf{g}_s \mathbf{z}_s \geq \mathbf{h}_s \quad \forall s \\
& \mathbf{y} \in \mathbf{Y} \\
& \mathbf{x}_s \geq 0 \quad \forall s \\
& \mathbf{z}_s \in \mathbf{Z} \quad \forall s
\end{align} $$

where the $\mathbf{y}$ is vector of integer variables.

Master Problem:

$$ \begin{align}
\min \quad& \mathbf{f}^{T} \mathbf{y} + \sum_{s \in \Omega} \pi_s q_s(\mathbf{y}) \\
\text{s.t.} \quad& \overline{\mathbf{u}_j^r}^T (\mathbf{h}_s - \mathbf{T}_s \mathbf{y}) \leq 0 \quad \forall j \\
& \overline{\mathbf{u}_i^p}^T (\mathbf{h}_s - \mathbf{T}_s \mathbf{y}) \leq q_s(\mathbf{y}) \quad \forall i \\
& \mathbf{y} \in \mathbf{Y}
\end{align} $$

Sub-problem for each scenario:

$$ \begin{align}
q_s(\mathbf{y}) = \min \quad & \mathbf{d}^{T}_s \mathbf{z}_s + \mathbf{c}_s^T \mathbf{x}_s \\
\text{s.t.} \quad & \mathbf{g}_s \mathbf{z}_s + \mathbf{w}_s \mathbf{x}_s \geq \mathbf{h}_s - \mathbf{T}_s \overline{\mathbf{y}} \\
& \mathbf{x}_s \geq 0
\end{align} $$

which is a standard MILP problem.

So we use the benders algorithm again. The Sub-Mas problem is:

$$ \begin{align}
q_s(\mathbf{y}) = \min \quad & \mathbf{d}^{T}_s \mathbf{z}_s + p_s(\mathbf{z}_s) \\
\text{s.t.} \quad & \overline{\mathbf{v}_m^p}^T \left[\left(\mathbf{h}_s - \mathbf{T}_s \overline{\mathbf{y}} \right) - \mathbf{g}_s \overline{\mathbf{z}_s} \right] \leq p_s(\mathbf{z}_s) \quad \forall m \\
& \overline{\mathbf{v}_n^r}^T \left[\left(\mathbf{h}_s - \mathbf{T}_s \overline{\mathbf{y}} \right) - \mathbf{g}_s \overline{\mathbf{z}_s} \right] \leq 0 \quad \forall n \\
& \mathbf{x}_s \geq 0
\end{align} $$

Sub-Sub-problem for each scenario:

$$ \begin{align}
p_s(\mathbf{y}) = \min \quad & \mathbf{c}_s^T \mathbf{x}_s \\
\text{s.t.} \quad & \mathbf{w}_s \mathbf{x}_s \geq \left(\mathbf{h}_s - \mathbf{T}_s \overline{\mathbf{y}} \right) - \mathbf{g}_s \overline{\mathbf{z}_s}  \\
& \mathbf{x}_s \geq 0
\end{align} $$

The dual function of $p_s(\mathbf{y})$ is:

$$ \begin{align}
p_s^d(\mathbf{y}) = \max \quad & \left[\left(\mathbf{h}_s - \mathbf{T}_s \overline{\mathbf{y}} \right) - \mathbf{g}_s \overline{\mathbf{z}_s} \right]^{T} \mathbf{v} \\
\text{s.t.} \quad & \mathbf{w}_s^{T} \mathbf{v} \leq \mathbf{c}_s \\
& \mathbf{v} \geq 0
\end{align} $$
