
## Dynamic Inconsistency

> In economics, dynamic inconsistency or time inconsistency is a situation in which a decision-maker's preferences change over time in such a way that a preference can become inconsistent at another point in time. This can be thought of as there being many different "selves" within decision makers, with each "self" representing the decision-maker at a different point in time; the inconsistency occurs when not all preferences are aligned. [_Dynamic inconsistency, Wikipedia_]

> The classical economic model of intertemporal choice assumes that choices have no utility consequences other than the consumption events that result from those choices. For example, the pleasure of a decadent meal is assumed to arise from the meal itself and not the awareness, before the event, that it will take place. In practice, however, when a plan is made in advance – for instance a dinner reservation – there is a waiting period during which the future outcome is anticipated. Moreover, this period of anticipation might have its own affective consequences for the actor. The period between decision and outcome has received relatively little consideration from economic researchers because economic models typically do not treat purely mental events as intrinsic sources of utility. [_berns2007intertemporal_]

### Reservation-Realization

1. __brocas2009dynamic__: Dynamic inconsistency and choice
2. __chatterjee2009dual__: A “Dual Self” Representation for Stochastic Temptation
3. __berns2007intertemporal__: Inter-temporal choice – toward an integrative framework `from the perspective of neuro-economics`

> The premise is simply that observed behavior reveals the existence of internal conflicts between objectives. A natural way of modelling such conflicts is to represent the individual as a collection of sub-entities, each pursuing one objective. [_brocas2009dynamic_]

> To be more precise, we consider the following thought experiment. In the first period, a decision maker chooses a menu consisting of a list of goods (or bundles). In the second period, he chooses an element from the menu. [_brocas2009dynamic_]

Collections: [_brocas2009dynamic_]

- earlier selves may have imperfect knowledge of the preferences of future selves
- it is natural to describe an individual as an entity with multiple intra-personal conflicts both within and between periods of time
