---
editor_options:
  chunk_output_type: console
# output: bookdown::gitbook
# bibliography: "../web/book.bib"
---

## Principal-Agent Problem (PA)

> The principal–agent problem, in political science and economics (also known as agency dilemma or the agency problem) occurs when one person or entity (the "agent"), is able to make decisions and/or take actions on behalf of, or that impact, another person or entity: the "principal". This dilemma exists in circumstances where agents are motivated to act in their own best interests, which are contrary to those of their principals, and is an example of moral hazard. [_Principal-Agent Problem, Wikipedia_]

### Application in Management of Energy Efficiency

> The "principal–agent problem" has also been discussed in the context of energy consumption by Jaffe and Stavins in 1994. They were attempting to catalog market and non-market barriers to energy efficiency adoption. In efficiency terms, a market failure arises when a technology which is both cost-effective and saves energy is not implemented. Jaffe and Stavins describe the common case of the landlord-tenant problem with energy issues as a principal–agent problem. "[I]f the potential adopter is not the party that pays the energy bill, then good information in the hands of the potential adopter may not be sufficient for optimal diffusion; adoption will only occur if the adopter can recover the investment from the party that enjoys the energy savings. Thus, if it is difficult for the possessor of information to convey it credibly to the party that benefits from reduced energy use, a principal/agent problem arises." [_Principal-Agent Problem, Wikipedia_]

- __tanaka2007mind__ Mind the gap: quantifying principal-agent problems in energy efficiency
- __jaffe1994energy__ The energy efficiency gap: what does it mean?

### Multiple Principal Problem (MP)

> The multiple principal problem, also known as the common agency problem, the multiple accountabilities problem, or the problem of serving two masters, is an extension of the principal-agent problem that explains problems that can occur when one person or entity acts on behalf of multiple other persons or entities. Specifically, the multiple principal problem states that when one person or entity (the "agent") is able to make decisions and / or take actions on behalf of, or that impact, multiple other entities: the "principals", the existence of asymmetric information and self-interest and moral hazard among the parties can cause the agent's behavior to differ substantially from what is in the joint principals' interest, bringing large inefficiencies. The multiple principal problem has been used to explain inefficiency in many types of cooperation, particularly in the public sector, including in parliaments, ministries, agencies, inter-municipal cooperation, and public-private partnerships, although the multiple principal problem also occurs in firms with multiple shareholders. [_Multiple Principal Problem, Wikipedia_]
