---
editor_options:
  chunk_output_type: console
# output: bookdown::gitbook
# bibliography: "../web/book.bib"
---

## Virtual Power Plant (VPP) {#VPP}

> VPP is a cluster of dispersed generating units, flexible loads, and storage systems that are grouped in order to operate as a single entity. [@morales2013integrating]

VPP operators have direct control over all units.

### Components of VPP {-}

- dispatchable generators
- responsive loads
- storage
- stochastic generators

### Operation of VPP: Profit-Maximization Problem {-}

When point forecasts are used, the problem becomes:

$$ \begin{align} \max_{\Xi} \quad & \rho = \sum_{t=1}^{T} \left[ \lambda^{\mathrm{D}}(t) P^{\mathrm{D}}(t) \tau - \sum_{i \in I}\left[C_{i}\left(E_{G i}(t)\right) \right. \right. \\
& \qquad \left.\left.+C_{i}^{\mathrm{SU}}(t) + C_{i}^{\mathrm{SD}}(t) \right] + \sum_{j \in J} U_{j} \left( E_{L j}(t) \right) \right] \\
\text{s.t.} \quad & \sum_{i \in I} E_{G i}(t)+\left(\sum_{q \in Q} \widehat{P}_{W q}(t)+\sum_{k \in K} P_{S k}^{d}(t)\right) \tau = \\
& \qquad \sum_{j \in J} E_{L j}(t) \quad + \left(\sum_{k \in K} P_{S k}^{c}(t)+P^{\mathrm{D}}(t)\right) \tau, \quad \forall t=1, \ldots, T \\
& G_{i}\left(P_{G i}, E_{G i}, v_{i}\right) \leq 0, \quad \forall i \in I \\
& v_{i} \in\{0,1\}^{T}, \quad \forall i \in I \\
& L_{j}\left(P_{L j}, E_{L j}\right) \leq 0, \quad \forall j \in J \\
& S_{k}\left(P_{S k}^{c}, P_{S k}^{d}, E_{S k}\right) \leq 0, \quad \forall k \in K
\end{align} $$

while the problem needs stochastic programming or robust programming when scenarios or interval forecasts are used respectively.

### Cost Allocation Problem {-}

The costs and profits must be distributed in a fair way.

### Spatial Models {-}


> Due to the dispersed nature of these resources, there is only one infrastructure “branched” enough to reach all of them: the distribution grid. Consequently, the management of VPPs will also call, among other things, for: [@morales2013integrating]
> 1. The enhancement of the control and monitoring of the distribution network to guarantee the performance, reliability, and security of the electricity supply.
> 2. The modeling, design and test of advanced components acting actively in the grid such as generators, transformers, smart meters, cables, breakers, insulators, power electronics, and converters.
> 3. The development of procedures to identify weaknesses in the distribution grid and propose guidelines for its reinforcement and expansion.

### Franchise Agreements and Cooperative Games {-}

> Cooperative games are often analyzed through the framework of cooperative game theory, which focuses on predicting which coalitions will form, the joint actions that groups take and the resulting collective payoffs. [@wiki:cooperative]

### Research Projects

- [@mashhour2011bidding, @mashhour2011bidding2]
  * The optimization problem is a nonlinear mixed-integer programming with inter-temporal constraints.
  * GA is used to solve the optimization problem.
