
## Dynamic Pricing

> Dynamic posted prices are also take-it-or-leave-it prices, where the seller dynamically changes prices over time (intertemporal prices) based on factors such as time of sale, demand information, and supply availability. [@elmaghraby2003dynamic]

### Initial Endowment

The procurement problem is not considered. For a target unit, the seller is endowed initially with an inventory. There is no way to replenish the inventory.

By the end of the selling season, leftover units have lowest values.

> Our consideration of limited inventory is motivated, in part, by the operational conditions in which supply chains of seasonal products function. For example, distant supplier locations, long production lead times, tight capacity constraints, and relatively short sales seasons may greatly limit the ability of retailers to replenish their inventory during a sales season. [@aviv2008optimal]

> This model is applicable to different industries, including travel (airplane seats and hotel rooms), retailing (fashion apparel and seasonal goods), and entertainment (concert and football tickets). [@su2007intertemporal]

### Market Segmentation

> The key to profit-enhancing pricing plans is the ability to engage in price discrimination via what economists call market segmentation. [@shy2008how]

### as a Marketing Strategy

> Scarcity of goods could also originate from deliberate market- ing strategies. For example, Zara, a large Spanish producer and retailer of fashion goods, limits the number of clothing items in their stores to create a sense of urgency among consumers. [@aviv2008optimal]

### Sellers' Commitment

Two reasons:

> If consumers observe that a certain service provider sells discounted tickets at the last minute, they may be deterred from making early reservations. Thus, service providers may suffer from a bad reputation if they often practice last-minute discounts. This is known as the sellers’ commitment problem. That is, in the short run, service providers may find it profitable to sell last-minute unbooked capacity at a lower price just to fill up the entire capacity. However, long-run considerations, such as reputation effect, prevent such practices. [@shy2008how]

> Reservations match supply with demand and permit 100% utilization, while service queues require slack capacity operating at less than 100%. Because of such inefficiency in queues, the firm should not allocate any capacity to serve walk-ins unless the walk-in customers pay higher price than reservation customers do. [@oh2018reservation]


### New Information

> Between the two time points, random demand is realized and publicly observed. Alternatively, we may assume that a market demand signal is publicly observed and that the signal is sufficiently informative for all parties to perfectly infer demand. [@su2010optimal]


### for Binary Purchase

In every decision epoch, customers have only two possible states: buy or not buy.

- [@zhao2010pre] Zhao, X., & Stecke, K. E. (2010). Pre‐orders for new to‐be‐released products considering consumer loss aversion. Production and Operations Management, 19(2), 198-215.
  * Two-period setting: advance selling and spot selling. So the price is not dynamic.
  * Initial procurement is considered.
  * Customers are not certain about their valuation in the advance selling season.

- [@prasad2011advance] Prasad, A., Stecke, K. E., & Zhao, X. (2011). Advance selling by a newsvendor retailer. Production and Operations Management, 20(1), 129-142.
  * Two-period setting
